### ISSUE TITLE
Documentation Menu not working properly on mobile screens

### ISSUE THREAD

**Issue by allanfreitas** [tailwindcss/docs#11] opened 2018-03-21 15:03 UTC
https://tailwindcss.com/docs/flexbox-justify-content

![image](https://user-images.githubusercontent.com/304086/37717526-7feb6db6-2cff-11e8-9f92-b1822eaaab87.png)

The menu doesn't stays with the Navbar.

![image](https://user-images.githubusercontent.com/304086/37717670-c4191f42-2cff-11e8-8154-1f23d946568f.png)

**Comment by hacknug** [comment] 2018-03-25 15:12
I don't see what the issue is. Every item on the sidebar shows up there and the menu is scrollable so you can see them all perfectly fine. Maybe you'd like this to have a different design?

**Comment by fedeTibaldo** [comment] 2018-03-26 17:03
I think is a design decision as well.

**Comment by allanfreitas** [comment] 2018-03-26 17:16
@hacknug @fedeTibaldo 

On click on the menu icon, this doesn't have to show up the top of the menu?

If it´s not a bug, please you can close the issue.

**Comment by fedeTibaldo** [comment] 2018-03-26 18:08
@allanfreitas Now I see what you mean.

I think an anchor to the top would fix this strange experience, although it would create even another strange experience: when closing the menu, the scrolling progress might have been reset.

When balancing the pros and cons however, I think it's more frustrating not seeing the menu at all than finding out that you got teleported to the top again when you close it.

On top of this speculation, when someone opens the menu, he/she probably clicks on a link as well, effectively leaving the page.
Moreover, if the user is experienced enough, he/she knows that pressing the back button would fix the jump phenomenon.

So yeah, it's not a bug, but the overall experience could be refined and redefined.

**Closed** 2018-03-26 19:41 UTC
